// Code generated by protoc-gen-go. DO NOT EDIT.
// source: synerex.proto

package api

import (
	context "context"
	fmt "fmt"
	agv "github.com/gitsakaki/synerex/synerex_alpha/api/agv"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	adservice "github.com/synerex/synerex_alpha/api/adservice"
	fleet "github.com/synerex/synerex_alpha/api/fleet"
	library "github.com/synerex/synerex_alpha/api/library"
	marketing "github.com/synerex/synerex_alpha/api/marketing"
	ptransit "github.com/synerex/synerex_alpha/api/ptransit"
	rideshare "github.com/synerex/synerex_alpha/api/rideshare"
	routing "github.com/synerex/synerex_alpha/api/routing"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChannelType int32

const (
	ChannelType_NONE              ChannelType = 0
	ChannelType_RIDE_SHARE        ChannelType = 1
	ChannelType_AD_SERVICE        ChannelType = 2
	ChannelType_LIB_SERVICE       ChannelType = 3
	ChannelType_PT_SERVICE        ChannelType = 4
	ChannelType_ROUTING_SERVICE   ChannelType = 5
	ChannelType_MARKETING_SERVICE ChannelType = 6
	ChannelType_AGV_SERVICE       ChannelType = 7
	ChannelType_END               ChannelType = 10
)

var ChannelType_name = map[int32]string{
	0:  "NONE",
	1:  "RIDE_SHARE",
	2:  "AD_SERVICE",
	3:  "LIB_SERVICE",
	4:  "PT_SERVICE",
	5:  "ROUTING_SERVICE",
	6:  "MARKETING_SERVICE",
	7:  "AGV_SERVICE",
	10: "END",
}

var ChannelType_value = map[string]int32{
	"NONE":              0,
	"RIDE_SHARE":        1,
	"AD_SERVICE":        2,
	"LIB_SERVICE":       3,
	"PT_SERVICE":        4,
	"ROUTING_SERVICE":   5,
	"MARKETING_SERVICE": 6,
	"AGV_SERVICE":       7,
	"END":               10,
}

func (x ChannelType) String() string {
	return proto.EnumName(ChannelType_name, int32(x))
}

func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{0}
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ConfirmResponse struct {
	Ok                   bool               `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MbusId               uint64             `protobuf:"fixed64,2,opt,name=mbus_id,json=mbusId,proto3" json:"mbus_id,omitempty"`
	Wait                 *duration.Duration `protobuf:"bytes,3,opt,name=wait,proto3" json:"wait,omitempty"`
	Err                  string             `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ConfirmResponse) Reset()         { *m = ConfirmResponse{} }
func (m *ConfirmResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmResponse) ProtoMessage()    {}
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{1}
}

func (m *ConfirmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmResponse.Unmarshal(m, b)
}
func (m *ConfirmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmResponse.Merge(m, src)
}
func (m *ConfirmResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmResponse.Size(m)
}
func (m *ConfirmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmResponse proto.InternalMessageInfo

func (m *ConfirmResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ConfirmResponse) GetMbusId() uint64 {
	if m != nil {
		return m.MbusId
	}
	return 0
}

func (m *ConfirmResponse) GetWait() *duration.Duration {
	if m != nil {
		return m.Wait
	}
	return nil
}

func (m *ConfirmResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Supply struct {
	Id         uint64               `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId   uint64               `protobuf:"fixed64,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId   uint64               `protobuf:"fixed64,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Type       ChannelType          `protobuf:"varint,4,opt,name=type,proto3,enum=api.ChannelType" json:"type,omitempty"`
	SupplyName string               `protobuf:"bytes,5,opt,name=supply_name,json=supplyName,proto3" json:"supply_name,omitempty"`
	Ts         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	//message content = 7; // json
	ArgJson string `protobuf:"bytes,7,opt,name=arg_json,json=argJson,proto3" json:"arg_json,omitempty"`
	MbusId  uint64 `protobuf:"fixed64,8,opt,name=mbus_id,json=mbusId,proto3" json:"mbus_id,omitempty"`
	// Types that are valid to be assigned to ArgOneof:
	//	*Supply_Arg_Fleet
	//	*Supply_Arg_RideShare
	//	*Supply_Arg_AdService
	//	*Supply_Arg_LibService
	//	*Supply_Arg_PTService
	//	*Supply_Arg_RoutingService
	//	*Supply_Arg_MarketingService
	//	*Supply_Arg_PTgtfs
	//	*Supply_Arg_AgvService
	ArgOneof             isSupply_ArgOneof `protobuf_oneof:"arg_oneof"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Supply) Reset()         { *m = Supply{} }
func (m *Supply) String() string { return proto.CompactTextString(m) }
func (*Supply) ProtoMessage()    {}
func (*Supply) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{2}
}

func (m *Supply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Supply.Unmarshal(m, b)
}
func (m *Supply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Supply.Marshal(b, m, deterministic)
}
func (m *Supply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Supply.Merge(m, src)
}
func (m *Supply) XXX_Size() int {
	return xxx_messageInfo_Supply.Size(m)
}
func (m *Supply) XXX_DiscardUnknown() {
	xxx_messageInfo_Supply.DiscardUnknown(m)
}

var xxx_messageInfo_Supply proto.InternalMessageInfo

func (m *Supply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Supply) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Supply) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Supply) GetType() ChannelType {
	if m != nil {
		return m.Type
	}
	return ChannelType_NONE
}

func (m *Supply) GetSupplyName() string {
	if m != nil {
		return m.SupplyName
	}
	return ""
}

func (m *Supply) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Supply) GetArgJson() string {
	if m != nil {
		return m.ArgJson
	}
	return ""
}

func (m *Supply) GetMbusId() uint64 {
	if m != nil {
		return m.MbusId
	}
	return 0
}

type isSupply_ArgOneof interface {
	isSupply_ArgOneof()
}

type Supply_Arg_Fleet struct {
	Arg_Fleet *fleet.Fleet `protobuf:"bytes,10,opt,name=arg_Fleet,json=argFleet,proto3,oneof"`
}

type Supply_Arg_RideShare struct {
	Arg_RideShare *rideshare.RideShare `protobuf:"bytes,11,opt,name=arg_RideShare,json=argRideShare,proto3,oneof"`
}

type Supply_Arg_AdService struct {
	Arg_AdService *adservice.AdService `protobuf:"bytes,12,opt,name=arg_AdService,json=argAdService,proto3,oneof"`
}

type Supply_Arg_LibService struct {
	Arg_LibService *library.LibService `protobuf:"bytes,13,opt,name=arg_LibService,json=argLibService,proto3,oneof"`
}

type Supply_Arg_PTService struct {
	Arg_PTService *ptransit.PTService `protobuf:"bytes,14,opt,name=arg_PTService,json=argPTService,proto3,oneof"`
}

type Supply_Arg_RoutingService struct {
	Arg_RoutingService *routing.RoutingService `protobuf:"bytes,15,opt,name=arg_RoutingService,json=argRoutingService,proto3,oneof"`
}

type Supply_Arg_MarketingService struct {
	Arg_MarketingService *marketing.MarketingService `protobuf:"bytes,16,opt,name=arg_MarketingService,json=argMarketingService,proto3,oneof"`
}

type Supply_Arg_PTgtfs struct {
	Arg_PTgtfs *ptransit.PTgtfs `protobuf:"bytes,17,opt,name=arg_PTgtfs,json=argPTgtfs,proto3,oneof"`
}

type Supply_Arg_AgvService struct {
	Arg_AgvService *agv.AgvService `protobuf:"bytes,18,opt,name=arg_AgvService,json=argAgvService,proto3,oneof"`
}

func (*Supply_Arg_Fleet) isSupply_ArgOneof() {}

func (*Supply_Arg_RideShare) isSupply_ArgOneof() {}

func (*Supply_Arg_AdService) isSupply_ArgOneof() {}

func (*Supply_Arg_LibService) isSupply_ArgOneof() {}

func (*Supply_Arg_PTService) isSupply_ArgOneof() {}

func (*Supply_Arg_RoutingService) isSupply_ArgOneof() {}

func (*Supply_Arg_MarketingService) isSupply_ArgOneof() {}

func (*Supply_Arg_PTgtfs) isSupply_ArgOneof() {}

func (*Supply_Arg_AgvService) isSupply_ArgOneof() {}

func (m *Supply) GetArgOneof() isSupply_ArgOneof {
	if m != nil {
		return m.ArgOneof
	}
	return nil
}

func (m *Supply) GetArg_Fleet() *fleet.Fleet {
	if x, ok := m.GetArgOneof().(*Supply_Arg_Fleet); ok {
		return x.Arg_Fleet
	}
	return nil
}

func (m *Supply) GetArg_RideShare() *rideshare.RideShare {
	if x, ok := m.GetArgOneof().(*Supply_Arg_RideShare); ok {
		return x.Arg_RideShare
	}
	return nil
}

func (m *Supply) GetArg_AdService() *adservice.AdService {
	if x, ok := m.GetArgOneof().(*Supply_Arg_AdService); ok {
		return x.Arg_AdService
	}
	return nil
}

func (m *Supply) GetArg_LibService() *library.LibService {
	if x, ok := m.GetArgOneof().(*Supply_Arg_LibService); ok {
		return x.Arg_LibService
	}
	return nil
}

func (m *Supply) GetArg_PTService() *ptransit.PTService {
	if x, ok := m.GetArgOneof().(*Supply_Arg_PTService); ok {
		return x.Arg_PTService
	}
	return nil
}

func (m *Supply) GetArg_RoutingService() *routing.RoutingService {
	if x, ok := m.GetArgOneof().(*Supply_Arg_RoutingService); ok {
		return x.Arg_RoutingService
	}
	return nil
}

func (m *Supply) GetArg_MarketingService() *marketing.MarketingService {
	if x, ok := m.GetArgOneof().(*Supply_Arg_MarketingService); ok {
		return x.Arg_MarketingService
	}
	return nil
}

func (m *Supply) GetArg_PTgtfs() *ptransit.PTgtfs {
	if x, ok := m.GetArgOneof().(*Supply_Arg_PTgtfs); ok {
		return x.Arg_PTgtfs
	}
	return nil
}

func (m *Supply) GetArg_AgvService() *agv.AgvService {
	if x, ok := m.GetArgOneof().(*Supply_Arg_AgvService); ok {
		return x.Arg_AgvService
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Supply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Supply_Arg_Fleet)(nil),
		(*Supply_Arg_RideShare)(nil),
		(*Supply_Arg_AdService)(nil),
		(*Supply_Arg_LibService)(nil),
		(*Supply_Arg_PTService)(nil),
		(*Supply_Arg_RoutingService)(nil),
		(*Supply_Arg_MarketingService)(nil),
		(*Supply_Arg_PTgtfs)(nil),
		(*Supply_Arg_AgvService)(nil),
	}
}

type Demand struct {
	Id         uint64               `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId   uint64               `protobuf:"fixed64,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId   uint64               `protobuf:"fixed64,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Type       ChannelType          `protobuf:"varint,4,opt,name=type,proto3,enum=api.ChannelType" json:"type,omitempty"`
	DemandName string               `protobuf:"bytes,5,opt,name=demand_name,json=demandName,proto3" json:"demand_name,omitempty"`
	Ts         *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	//message content = 7; // json
	ArgJson string `protobuf:"bytes,7,opt,name=arg_json,json=argJson,proto3" json:"arg_json,omitempty"`
	MbusId  uint64 `protobuf:"fixed64,8,opt,name=mbus_id,json=mbusId,proto3" json:"mbus_id,omitempty"`
	// Types that are valid to be assigned to ArgOneof:
	//	*Demand_Arg_Fleet
	//	*Demand_Arg_RideShare
	//	*Demand_Arg_AdService
	//	*Demand_Arg_LibService
	//	*Demand_Arg_PTService
	//	*Demand_Arg_RoutingService
	//	*Demand_Arg_MarketingService
	//	*Demand_Arg_PTgtfs
	//	*Demand_Arg_AgvService
	ArgOneof             isDemand_ArgOneof `protobuf_oneof:"arg_oneof"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Demand) Reset()         { *m = Demand{} }
func (m *Demand) String() string { return proto.CompactTextString(m) }
func (*Demand) ProtoMessage()    {}
func (*Demand) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{3}
}

func (m *Demand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demand.Unmarshal(m, b)
}
func (m *Demand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demand.Marshal(b, m, deterministic)
}
func (m *Demand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demand.Merge(m, src)
}
func (m *Demand) XXX_Size() int {
	return xxx_messageInfo_Demand.Size(m)
}
func (m *Demand) XXX_DiscardUnknown() {
	xxx_messageInfo_Demand.DiscardUnknown(m)
}

var xxx_messageInfo_Demand proto.InternalMessageInfo

func (m *Demand) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Demand) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Demand) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Demand) GetType() ChannelType {
	if m != nil {
		return m.Type
	}
	return ChannelType_NONE
}

func (m *Demand) GetDemandName() string {
	if m != nil {
		return m.DemandName
	}
	return ""
}

func (m *Demand) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Demand) GetArgJson() string {
	if m != nil {
		return m.ArgJson
	}
	return ""
}

func (m *Demand) GetMbusId() uint64 {
	if m != nil {
		return m.MbusId
	}
	return 0
}

type isDemand_ArgOneof interface {
	isDemand_ArgOneof()
}

type Demand_Arg_Fleet struct {
	Arg_Fleet *fleet.Fleet `protobuf:"bytes,10,opt,name=arg_Fleet,json=argFleet,proto3,oneof"`
}

type Demand_Arg_RideShare struct {
	Arg_RideShare *rideshare.RideShare `protobuf:"bytes,11,opt,name=arg_RideShare,json=argRideShare,proto3,oneof"`
}

type Demand_Arg_AdService struct {
	Arg_AdService *adservice.AdService `protobuf:"bytes,12,opt,name=arg_AdService,json=argAdService,proto3,oneof"`
}

type Demand_Arg_LibService struct {
	Arg_LibService *library.LibService `protobuf:"bytes,13,opt,name=arg_LibService,json=argLibService,proto3,oneof"`
}

type Demand_Arg_PTService struct {
	Arg_PTService *ptransit.PTService `protobuf:"bytes,14,opt,name=arg_PTService,json=argPTService,proto3,oneof"`
}

type Demand_Arg_RoutingService struct {
	Arg_RoutingService *routing.RoutingService `protobuf:"bytes,15,opt,name=arg_RoutingService,json=argRoutingService,proto3,oneof"`
}

type Demand_Arg_MarketingService struct {
	Arg_MarketingService *marketing.MarketingService `protobuf:"bytes,16,opt,name=arg_MarketingService,json=argMarketingService,proto3,oneof"`
}

type Demand_Arg_PTgtfs struct {
	Arg_PTgtfs *ptransit.PTgtfs `protobuf:"bytes,17,opt,name=arg_PTgtfs,json=argPTgtfs,proto3,oneof"`
}

type Demand_Arg_AgvService struct {
	Arg_AgvService *agv.AgvService `protobuf:"bytes,18,opt,name=arg_AgvService,json=argAgvService,proto3,oneof"`
}

func (*Demand_Arg_Fleet) isDemand_ArgOneof() {}

func (*Demand_Arg_RideShare) isDemand_ArgOneof() {}

func (*Demand_Arg_AdService) isDemand_ArgOneof() {}

func (*Demand_Arg_LibService) isDemand_ArgOneof() {}

func (*Demand_Arg_PTService) isDemand_ArgOneof() {}

func (*Demand_Arg_RoutingService) isDemand_ArgOneof() {}

func (*Demand_Arg_MarketingService) isDemand_ArgOneof() {}

func (*Demand_Arg_PTgtfs) isDemand_ArgOneof() {}

func (*Demand_Arg_AgvService) isDemand_ArgOneof() {}

func (m *Demand) GetArgOneof() isDemand_ArgOneof {
	if m != nil {
		return m.ArgOneof
	}
	return nil
}

func (m *Demand) GetArg_Fleet() *fleet.Fleet {
	if x, ok := m.GetArgOneof().(*Demand_Arg_Fleet); ok {
		return x.Arg_Fleet
	}
	return nil
}

func (m *Demand) GetArg_RideShare() *rideshare.RideShare {
	if x, ok := m.GetArgOneof().(*Demand_Arg_RideShare); ok {
		return x.Arg_RideShare
	}
	return nil
}

func (m *Demand) GetArg_AdService() *adservice.AdService {
	if x, ok := m.GetArgOneof().(*Demand_Arg_AdService); ok {
		return x.Arg_AdService
	}
	return nil
}

func (m *Demand) GetArg_LibService() *library.LibService {
	if x, ok := m.GetArgOneof().(*Demand_Arg_LibService); ok {
		return x.Arg_LibService
	}
	return nil
}

func (m *Demand) GetArg_PTService() *ptransit.PTService {
	if x, ok := m.GetArgOneof().(*Demand_Arg_PTService); ok {
		return x.Arg_PTService
	}
	return nil
}

func (m *Demand) GetArg_RoutingService() *routing.RoutingService {
	if x, ok := m.GetArgOneof().(*Demand_Arg_RoutingService); ok {
		return x.Arg_RoutingService
	}
	return nil
}

func (m *Demand) GetArg_MarketingService() *marketing.MarketingService {
	if x, ok := m.GetArgOneof().(*Demand_Arg_MarketingService); ok {
		return x.Arg_MarketingService
	}
	return nil
}

func (m *Demand) GetArg_PTgtfs() *ptransit.PTgtfs {
	if x, ok := m.GetArgOneof().(*Demand_Arg_PTgtfs); ok {
		return x.Arg_PTgtfs
	}
	return nil
}

func (m *Demand) GetArg_AgvService() *agv.AgvService {
	if x, ok := m.GetArgOneof().(*Demand_Arg_AgvService); ok {
		return x.Arg_AgvService
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Demand) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Demand_Arg_Fleet)(nil),
		(*Demand_Arg_RideShare)(nil),
		(*Demand_Arg_AdService)(nil),
		(*Demand_Arg_LibService)(nil),
		(*Demand_Arg_PTService)(nil),
		(*Demand_Arg_RoutingService)(nil),
		(*Demand_Arg_MarketingService)(nil),
		(*Demand_Arg_PTgtfs)(nil),
		(*Demand_Arg_AgvService)(nil),
	}
}

type Target struct {
	Id                   uint64             `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId             uint64             `protobuf:"fixed64,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId             uint64             `protobuf:"fixed64,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Type                 ChannelType        `protobuf:"varint,4,opt,name=type,proto3,enum=api.ChannelType" json:"type,omitempty"`
	Wait                 *duration.Duration `protobuf:"bytes,5,opt,name=wait,proto3" json:"wait,omitempty"`
	MbusId               uint64             `protobuf:"fixed64,6,opt,name=mbus_id,json=mbusId,proto3" json:"mbus_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{4}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Target) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Target) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Target) GetType() ChannelType {
	if m != nil {
		return m.Type
	}
	return ChannelType_NONE
}

func (m *Target) GetWait() *duration.Duration {
	if m != nil {
		return m.Wait
	}
	return nil
}

func (m *Target) GetMbusId() uint64 {
	if m != nil {
		return m.MbusId
	}
	return 0
}

type Channel struct {
	ClientId             uint64      `protobuf:"fixed64,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Type                 ChannelType `protobuf:"varint,2,opt,name=type,proto3,enum=api.ChannelType" json:"type,omitempty"`
	ArgJson              string      `protobuf:"bytes,3,opt,name=arg_json,json=argJson,proto3" json:"arg_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{5}
}

func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (m *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(m, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Channel) GetType() ChannelType {
	if m != nil {
		return m.Type
	}
	return ChannelType_NONE
}

func (m *Channel) GetArgJson() string {
	if m != nil {
		return m.ArgJson
	}
	return ""
}

type Mbus struct {
	ClientId             uint64   `protobuf:"fixed64,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MbusId               uint64   `protobuf:"fixed64,2,opt,name=mbus_id,json=mbusId,proto3" json:"mbus_id,omitempty"`
	ArgJson              string   `protobuf:"bytes,3,opt,name=arg_json,json=argJson,proto3" json:"arg_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mbus) Reset()         { *m = Mbus{} }
func (m *Mbus) String() string { return proto.CompactTextString(m) }
func (*Mbus) ProtoMessage()    {}
func (*Mbus) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{6}
}

func (m *Mbus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mbus.Unmarshal(m, b)
}
func (m *Mbus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mbus.Marshal(b, m, deterministic)
}
func (m *Mbus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mbus.Merge(m, src)
}
func (m *Mbus) XXX_Size() int {
	return xxx_messageInfo_Mbus.Size(m)
}
func (m *Mbus) XXX_DiscardUnknown() {
	xxx_messageInfo_Mbus.DiscardUnknown(m)
}

var xxx_messageInfo_Mbus proto.InternalMessageInfo

func (m *Mbus) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Mbus) GetMbusId() uint64 {
	if m != nil {
		return m.MbusId
	}
	return 0
}

func (m *Mbus) GetArgJson() string {
	if m != nil {
		return m.ArgJson
	}
	return ""
}

type MbusMsg struct {
	MsgId                uint64   `protobuf:"fixed64,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId             uint64   `protobuf:"fixed64,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId             uint64   `protobuf:"fixed64,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MbusId               uint64   `protobuf:"fixed64,4,opt,name=mbus_id,json=mbusId,proto3" json:"mbus_id,omitempty"`
	MsgType              uint32   `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgInfo              string   `protobuf:"bytes,6,opt,name=msg_info,json=msgInfo,proto3" json:"msg_info,omitempty"`
	ArgJson              string   `protobuf:"bytes,7,opt,name=arg_json,json=argJson,proto3" json:"arg_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MbusMsg) Reset()         { *m = MbusMsg{} }
func (m *MbusMsg) String() string { return proto.CompactTextString(m) }
func (*MbusMsg) ProtoMessage()    {}
func (*MbusMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_64312b9648bb40d3, []int{7}
}

func (m *MbusMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MbusMsg.Unmarshal(m, b)
}
func (m *MbusMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MbusMsg.Marshal(b, m, deterministic)
}
func (m *MbusMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MbusMsg.Merge(m, src)
}
func (m *MbusMsg) XXX_Size() int {
	return xxx_messageInfo_MbusMsg.Size(m)
}
func (m *MbusMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MbusMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MbusMsg proto.InternalMessageInfo

func (m *MbusMsg) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MbusMsg) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *MbusMsg) GetTargetId() uint64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *MbusMsg) GetMbusId() uint64 {
	if m != nil {
		return m.MbusId
	}
	return 0
}

func (m *MbusMsg) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *MbusMsg) GetMsgInfo() string {
	if m != nil {
		return m.MsgInfo
	}
	return ""
}

func (m *MbusMsg) GetArgJson() string {
	if m != nil {
		return m.ArgJson
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.ChannelType", ChannelType_name, ChannelType_value)
	proto.RegisterType((*Response)(nil), "api.Response")
	proto.RegisterType((*ConfirmResponse)(nil), "api.ConfirmResponse")
	proto.RegisterType((*Supply)(nil), "api.Supply")
	proto.RegisterType((*Demand)(nil), "api.Demand")
	proto.RegisterType((*Target)(nil), "api.Target")
	proto.RegisterType((*Channel)(nil), "api.Channel")
	proto.RegisterType((*Mbus)(nil), "api.Mbus")
	proto.RegisterType((*MbusMsg)(nil), "api.MbusMsg")
}

func init() { proto.RegisterFile("synerex.proto", fileDescriptor_64312b9648bb40d3) }

var fileDescriptor_64312b9648bb40d3 = []byte{
	// 1070 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xeb, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0x75, 0xd7, 0x3e, 0x8e, 0x1d, 0x67, 0xd2, 0x28, 0x1b, 0x57, 0x22, 0x91, 0x85, 0xd4,
	0xa8, 0x6a, 0xed, 0x2a, 0x85, 0x7f, 0x08, 0x70, 0x12, 0x53, 0x1b, 0x92, 0x34, 0x1a, 0x9b, 0x22,
	0xf1, 0x27, 0x5a, 0x67, 0xc7, 0xdb, 0x25, 0xde, 0x8b, 0x66, 0xd6, 0x81, 0x88, 0x77, 0xe1, 0x05,
	0x78, 0x09, 0x7e, 0xf0, 0x08, 0x3c, 0x10, 0x9a, 0x33, 0x7b, 0xb5, 0x69, 0x48, 0x85, 0x04, 0x42,
	0xea, 0x9f, 0x78, 0xce, 0xed, 0x3b, 0x97, 0x3d, 0xdf, 0xee, 0x04, 0x9a, 0xe2, 0xce, 0x63, 0x9c,
	0xfd, 0xd4, 0x0b, 0xb8, 0x1f, 0xfa, 0xa4, 0x6c, 0x06, 0x4e, 0x67, 0xdf, 0xf6, 0x7d, 0x7b, 0xc1,
	0xfa, 0xa8, 0x9a, 0x2d, 0xe7, 0xfd, 0xd0, 0x71, 0x99, 0x08, 0x4d, 0x37, 0x50, 0x5e, 0x9d, 0x8f,
	0x56, 0x1d, 0xac, 0x25, 0x37, 0x43, 0xc7, 0xf7, 0x22, 0xfb, 0xd6, 0x7c, 0xc1, 0x58, 0xd8, 0xc7,
	0xbf, 0x91, 0x6a, 0x8f, 0x3b, 0x16, 0x13, 0x6f, 0x4d, 0xce, 0xfa, 0xc9, 0x29, 0x36, 0x99, 0x96,
	0x60, 0xfc, 0xd6, 0xb9, 0x66, 0xfd, 0xe4, 0x14, 0x99, 0x76, 0x16, 0xce, 0x8c, 0x9b, 0xfc, 0xae,
	0x1f, 0xfd, 0x46, 0xea, 0xdd, 0x20, 0xe4, 0xa6, 0x27, 0x9c, 0xb0, 0x1f, 0x1f, 0x62, 0x7f, 0xee,
	0x2f, 0x43, 0xc7, 0xb3, 0xfb, 0xd1, 0x6f, 0x9c, 0xc1, 0x35, 0xf9, 0x0d, 0x43, 0x43, 0x72, 0x8a,
	0x4c, 0x4d, 0xd3, 0xbe, 0xed, 0x9b, 0xf6, 0xad, 0x12, 0xbb, 0xcf, 0xa0, 0x46, 0x99, 0x08, 0x7c,
	0x4f, 0x30, 0xd2, 0x82, 0x92, 0x7f, 0x63, 0x14, 0x0f, 0x8a, 0x87, 0x35, 0x5a, 0xf2, 0x6f, 0x48,
	0x1b, 0xca, 0x8c, 0x73, 0xa3, 0x74, 0x50, 0x3c, 0xac, 0x53, 0x79, 0xec, 0xfe, 0x0c, 0x9b, 0x27,
	0xbe, 0x37, 0x77, 0xb8, 0xfb, 0xce, 0xa0, 0x5d, 0xd0, 0xdd, 0xd9, 0x52, 0x5c, 0x39, 0x16, 0x06,
	0x6a, 0x54, 0x93, 0xe2, 0xd8, 0x22, 0xcf, 0xa1, 0xf2, 0xa3, 0xe9, 0x84, 0x46, 0xf9, 0xa0, 0x78,
	0xd8, 0x38, 0xda, 0xeb, 0xa9, 0x91, 0xf6, 0xe2, 0x91, 0xf6, 0x4e, 0xa3, 0x91, 0x52, 0x74, 0x8b,
	0x93, 0x57, 0xd2, 0xe4, 0x7f, 0x68, 0xa0, 0x4d, 0x96, 0x41, 0xb0, 0xb8, 0x93, 0x49, 0x1d, 0x0b,
	0x93, 0x6a, 0xb4, 0xe4, 0x58, 0xe4, 0x31, 0xd4, 0x05, 0xf3, 0x2c, 0xc6, 0xd3, 0xb4, 0x35, 0xa5,
	0x18, 0xa3, 0x31, 0x34, 0xb9, 0xcd, 0x42, 0x69, 0x2c, 0x2b, 0xa3, 0x52, 0x8c, 0x2d, 0xf2, 0x31,
	0x54, 0xc2, 0xbb, 0x80, 0x61, 0x9e, 0xd6, 0x51, 0xbb, 0x67, 0x06, 0x4e, 0xef, 0xe4, 0xad, 0xe9,
	0x79, 0x6c, 0x31, 0xbd, 0x0b, 0x18, 0x45, 0x2b, 0xd9, 0x87, 0x86, 0xc0, 0xcc, 0x57, 0x9e, 0xe9,
	0x32, 0xa3, 0x8a, 0x45, 0x81, 0x52, 0x5d, 0x98, 0x2e, 0x23, 0x4f, 0xa1, 0x14, 0x0a, 0x43, 0xc3,
	0xd6, 0x3a, 0x6b, 0xad, 0x4d, 0xe3, 0x75, 0xa2, 0xa5, 0x50, 0x90, 0x3d, 0xa8, 0x99, 0xdc, 0xbe,
	0xfa, 0x41, 0xf8, 0x9e, 0xa1, 0x23, 0x92, 0x6e, 0x72, 0xfb, 0x6b, 0xe1, 0x7b, 0xd9, 0xe1, 0xd5,
	0x72, 0xc3, 0xeb, 0x43, 0x5d, 0xc6, 0x7c, 0x25, 0x17, 0xcc, 0x00, 0x4c, 0xa3, 0x6a, 0x55, 0x2b,
	0x87, 0xfa, 0x51, 0x81, 0x4a, 0x60, 0x3c, 0x93, 0x2f, 0xa0, 0x29, 0x03, 0xa8, 0x63, 0xb1, 0x89,
	0x5c, 0x3d, 0xa3, 0x81, 0x41, 0x06, 0x06, 0xa5, 0x0b, 0x99, 0xd8, 0x47, 0x05, 0xba, 0x61, 0x72,
	0x3b, 0x91, 0x63, 0x80, 0x81, 0x35, 0x51, 0x0b, 0x6a, 0x6c, 0x64, 0x00, 0xd2, 0xb5, 0x4d, 0xec,
	0x11, 0x40, 0x22, 0x93, 0x2f, 0xa1, 0x25, 0x01, 0xce, 0x9c, 0x59, 0x8c, 0xd0, 0x44, 0x84, 0x5d,
	0x44, 0x88, 0xf7, 0x3b, 0x35, 0x8f, 0x0a, 0x54, 0x66, 0x4c, 0x15, 0xe4, 0x73, 0x55, 0xc2, 0xe5,
	0x34, 0x06, 0x68, 0x65, 0x00, 0x12, 0x22, 0x24, 0xe6, 0xa8, 0x82, 0x44, 0x26, 0x67, 0x40, 0x70,
	0x06, 0x8a, 0x1a, 0x31, 0xc8, 0x26, 0x82, 0x3c, 0x56, 0x83, 0x88, 0x58, 0x93, 0x77, 0x19, 0x15,
	0xe8, 0x96, 0x9c, 0x45, 0x4e, 0x49, 0xa6, 0xf0, 0x48, 0xa2, 0x9d, 0xc7, 0x7c, 0x8a, 0xf1, 0xda,
	0x88, 0xb7, 0x8f, 0x78, 0x29, 0xd9, 0x56, 0xdd, 0x46, 0x05, 0xba, 0x6d, 0x72, 0x7b, 0x55, 0x4d,
	0x3e, 0x05, 0x50, 0x3d, 0xda, 0xe1, 0x5c, 0x18, 0x5b, 0x88, 0xf5, 0x68, 0xb5, 0x41, 0x69, 0x1b,
	0x15, 0x68, 0x1d, 0xbb, 0x93, 0x02, 0xf9, 0x4c, 0x0d, 0x77, 0x60, 0xdf, 0xc6, 0x65, 0x10, 0x0c,
	0xdd, 0x56, 0x8f, 0xc7, 0xbe, 0xed, 0xa5, 0xa6, 0x68, 0xb0, 0xa9, 0xe2, 0xb8, 0xa1, 0xb6, 0xc9,
	0xf7, 0x98, 0x3f, 0x47, 0x5a, 0x9d, 0x32, 0xd7, 0xf4, 0xac, 0xff, 0x82, 0x56, 0x16, 0x66, 0xce,
	0xd1, 0x4a, 0xa9, 0x3e, 0xd0, 0xea, 0x03, 0xad, 0xfe, 0xcf, 0xb4, 0xfa, 0xad, 0x08, 0xda, 0x14,
	0xe9, 0xf0, 0xaf, 0xd3, 0x2a, 0xfe, 0xd2, 0x56, 0x1f, 0xf6, 0xa5, 0xcd, 0xb0, 0x43, 0xcb, 0xb2,
	0xa3, 0x6b, 0x83, 0x1e, 0x81, 0xcb, 0xaa, 0xae, 0x17, 0x0e, 0xf3, 0xb0, 0x2a, 0xd5, 0x49, 0x4d,
	0x29, 0x32, 0x55, 0x95, 0xee, 0xad, 0x2a, 0xcb, 0xcf, 0x72, 0x8e, 0x9f, 0xdd, 0xef, 0xa0, 0x72,
	0x3e, 0x5b, 0x8a, 0xfb, 0xb3, 0xbc, 0xf3, 0x62, 0x71, 0x0f, 0xf0, 0xef, 0x45, 0xd0, 0x25, 0xf2,
	0xb9, 0xb0, 0xc9, 0x0e, 0x68, 0xae, 0xb0, 0x53, 0xe4, 0xaa, 0x2b, 0xec, 0xf1, 0x3f, 0x79, 0x18,
	0x99, 0x82, 0x2a, 0xab, 0x05, 0xc9, 0x4c, 0x38, 0x13, 0xf9, 0x0c, 0x9a, 0x54, 0x77, 0x85, 0x3d,
	0x8d, 0x86, 0x80, 0x45, 0x78, 0x73, 0x1f, 0x87, 0x5d, 0x47, 0xd3, 0xd8, 0x9b, 0xfb, 0xf7, 0xbc,
	0xbf, 0x9e, 0xfe, 0x52, 0x84, 0x46, 0x66, 0xa0, 0xa4, 0x06, 0x95, 0x8b, 0xd7, 0x17, 0xc3, 0x76,
	0x81, 0xb4, 0x00, 0xe8, 0xf8, 0x74, 0x78, 0x35, 0x19, 0x0d, 0xe8, 0xb0, 0x5d, 0x94, 0xf2, 0xe0,
	0xf4, 0x6a, 0x32, 0xa4, 0x6f, 0xc6, 0x27, 0xc3, 0x76, 0x89, 0x6c, 0x42, 0xe3, 0x6c, 0x7c, 0x9c,
	0x28, 0xca, 0xd2, 0xe1, 0x72, 0x9a, 0xc8, 0x15, 0xb2, 0x0d, 0x9b, 0xf4, 0xf5, 0xb7, 0xd3, 0xf1,
	0xc5, 0xab, 0x44, 0x59, 0x25, 0x3b, 0xb0, 0x75, 0x3e, 0xa0, 0xdf, 0x0c, 0x73, 0x6a, 0x4d, 0x82,
	0x0d, 0x5e, 0xbd, 0x49, 0x14, 0x3a, 0xd1, 0xa1, 0x3c, 0xbc, 0x38, 0x6d, 0xc3, 0xd1, 0xaf, 0x55,
	0xd0, 0x27, 0xea, 0x5e, 0x4d, 0x7a, 0xd0, 0xa2, 0xcc, 0x76, 0x44, 0xc8, 0x78, 0xf4, 0x59, 0x69,
	0xe0, 0x46, 0x28, 0xa1, 0xd3, 0x44, 0x21, 0xbe, 0x3e, 0x76, 0x0b, 0x59, 0xff, 0xe8, 0x76, 0xa7,
	0xfc, 0x95, 0xb0, 0xee, 0xff, 0x1c, 0x9a, 0x97, 0xdc, 0x0f, 0x7c, 0xc1, 0x1e, 0x04, 0x9f, 0xba,
	0x3f, 0x08, 0xfd, 0x13, 0x68, 0x52, 0x26, 0xdf, 0xc2, 0x79, 0x77, 0xc5, 0xe4, 0x8e, 0x7a, 0x85,
	0xac, 0x5c, 0x81, 0x73, 0x51, 0xb9, 0x9a, 0xfe, 0x26, 0xea, 0x25, 0x6c, 0x4c, 0xd8, 0x82, 0x5d,
	0x87, 0xef, 0x93, 0x2a, 0x09, 0x7a, 0x9f, 0x4c, 0x4f, 0x40, 0x8f, 0x94, 0x79, 0xff, 0xb5, 0xf6,
	0x5f, 0xc0, 0xe6, 0x64, 0x39, 0x13, 0xd7, 0xdc, 0x99, 0xc5, 0xad, 0x6c, 0x64, 0xf9, 0xdc, 0xc9,
	0x0e, 0xbb, 0x5b, 0x78, 0x51, 0xcc, 0x45, 0x44, 0x7d, 0xfc, 0x55, 0x84, 0x32, 0x61, 0xc4, 0x33,
	0x68, 0x26, 0x11, 0x48, 0xfb, 0x3a, 0x7a, 0xc8, 0x63, 0x67, 0x23, 0x39, 0x9e, 0x0b, 0x1b, 0xbd,
	0x0f, 0x41, 0x9f, 0x30, 0xcf, 0x92, 0x0c, 0xce, 0x19, 0xd7, 0x6b, 0x7f, 0x02, 0xf5, 0x93, 0x85,
	0x2f, 0xd6, 0x30, 0x57, 0x1d, 0x8f, 0xab, 0xdf, 0xcb, 0xff, 0xfa, 0x66, 0x1a, 0xbe, 0x10, 0x5f,
	0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0x31, 0xcd, 0x0c, 0x4f, 0x12, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SynerexClient is the client API for Synerex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SynerexClient interface {
	RegisterDemand(ctx context.Context, in *Demand, opts ...grpc.CallOption) (*Response, error)
	RegisterSupply(ctx context.Context, in *Supply, opts ...grpc.CallOption) (*Response, error)
	ProposeDemand(ctx context.Context, in *Demand, opts ...grpc.CallOption) (*Response, error)
	ProposeSupply(ctx context.Context, in *Supply, opts ...grpc.CallOption) (*Response, error)
	ReserveSupply(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error)
	ReserveDemand(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error)
	SelectSupply(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error)
	SelectDemand(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error)
	Confirm(ctx context.Context, in *Target, opts ...grpc.CallOption) (*Response, error)
	SubscribeDemand(ctx context.Context, in *Channel, opts ...grpc.CallOption) (Synerex_SubscribeDemandClient, error)
	SubscribeSupply(ctx context.Context, in *Channel, opts ...grpc.CallOption) (Synerex_SubscribeSupplyClient, error)
	SubscribeMbus(ctx context.Context, in *Mbus, opts ...grpc.CallOption) (Synerex_SubscribeMbusClient, error)
	SendMsg(ctx context.Context, in *MbusMsg, opts ...grpc.CallOption) (*Response, error)
	CloseMbus(ctx context.Context, in *Mbus, opts ...grpc.CallOption) (*Response, error)
}

type synerexClient struct {
	cc *grpc.ClientConn
}

func NewSynerexClient(cc *grpc.ClientConn) SynerexClient {
	return &synerexClient{cc}
}

func (c *synerexClient) RegisterDemand(ctx context.Context, in *Demand, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/RegisterDemand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) RegisterSupply(ctx context.Context, in *Supply, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/RegisterSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) ProposeDemand(ctx context.Context, in *Demand, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/ProposeDemand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) ProposeSupply(ctx context.Context, in *Supply, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/ProposeSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) ReserveSupply(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, "/api.Synerex/ReserveSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) ReserveDemand(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, "/api.Synerex/ReserveDemand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) SelectSupply(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, "/api.Synerex/SelectSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) SelectDemand(ctx context.Context, in *Target, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, "/api.Synerex/SelectDemand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) Confirm(ctx context.Context, in *Target, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/Confirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) SubscribeDemand(ctx context.Context, in *Channel, opts ...grpc.CallOption) (Synerex_SubscribeDemandClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Synerex_serviceDesc.Streams[0], "/api.Synerex/SubscribeDemand", opts...)
	if err != nil {
		return nil, err
	}
	x := &synerexSubscribeDemandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Synerex_SubscribeDemandClient interface {
	Recv() (*Demand, error)
	grpc.ClientStream
}

type synerexSubscribeDemandClient struct {
	grpc.ClientStream
}

func (x *synerexSubscribeDemandClient) Recv() (*Demand, error) {
	m := new(Demand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *synerexClient) SubscribeSupply(ctx context.Context, in *Channel, opts ...grpc.CallOption) (Synerex_SubscribeSupplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Synerex_serviceDesc.Streams[1], "/api.Synerex/SubscribeSupply", opts...)
	if err != nil {
		return nil, err
	}
	x := &synerexSubscribeSupplyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Synerex_SubscribeSupplyClient interface {
	Recv() (*Supply, error)
	grpc.ClientStream
}

type synerexSubscribeSupplyClient struct {
	grpc.ClientStream
}

func (x *synerexSubscribeSupplyClient) Recv() (*Supply, error) {
	m := new(Supply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *synerexClient) SubscribeMbus(ctx context.Context, in *Mbus, opts ...grpc.CallOption) (Synerex_SubscribeMbusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Synerex_serviceDesc.Streams[2], "/api.Synerex/SubscribeMbus", opts...)
	if err != nil {
		return nil, err
	}
	x := &synerexSubscribeMbusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Synerex_SubscribeMbusClient interface {
	Recv() (*MbusMsg, error)
	grpc.ClientStream
}

type synerexSubscribeMbusClient struct {
	grpc.ClientStream
}

func (x *synerexSubscribeMbusClient) Recv() (*MbusMsg, error) {
	m := new(MbusMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *synerexClient) SendMsg(ctx context.Context, in *MbusMsg, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *synerexClient) CloseMbus(ctx context.Context, in *Mbus, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.Synerex/CloseMbus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SynerexServer is the server API for Synerex service.
type SynerexServer interface {
	RegisterDemand(context.Context, *Demand) (*Response, error)
	RegisterSupply(context.Context, *Supply) (*Response, error)
	ProposeDemand(context.Context, *Demand) (*Response, error)
	ProposeSupply(context.Context, *Supply) (*Response, error)
	ReserveSupply(context.Context, *Target) (*ConfirmResponse, error)
	ReserveDemand(context.Context, *Target) (*ConfirmResponse, error)
	SelectSupply(context.Context, *Target) (*ConfirmResponse, error)
	SelectDemand(context.Context, *Target) (*ConfirmResponse, error)
	Confirm(context.Context, *Target) (*Response, error)
	SubscribeDemand(*Channel, Synerex_SubscribeDemandServer) error
	SubscribeSupply(*Channel, Synerex_SubscribeSupplyServer) error
	SubscribeMbus(*Mbus, Synerex_SubscribeMbusServer) error
	SendMsg(context.Context, *MbusMsg) (*Response, error)
	CloseMbus(context.Context, *Mbus) (*Response, error)
}

func RegisterSynerexServer(s *grpc.Server, srv SynerexServer) {
	s.RegisterService(&_Synerex_serviceDesc, srv)
}

func _Synerex_RegisterDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Demand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).RegisterDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/RegisterDemand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).RegisterDemand(ctx, req.(*Demand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_RegisterSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).RegisterSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/RegisterSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).RegisterSupply(ctx, req.(*Supply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_ProposeDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Demand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).ProposeDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/ProposeDemand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).ProposeDemand(ctx, req.(*Demand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_ProposeSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).ProposeSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/ProposeSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).ProposeSupply(ctx, req.(*Supply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_ReserveSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).ReserveSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/ReserveSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).ReserveSupply(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_ReserveDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).ReserveDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/ReserveDemand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).ReserveDemand(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_SelectSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).SelectSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/SelectSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).SelectSupply(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_SelectDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).SelectDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/SelectDemand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).SelectDemand(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/Confirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).Confirm(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_SubscribeDemand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Channel)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SynerexServer).SubscribeDemand(m, &synerexSubscribeDemandServer{stream})
}

type Synerex_SubscribeDemandServer interface {
	Send(*Demand) error
	grpc.ServerStream
}

type synerexSubscribeDemandServer struct {
	grpc.ServerStream
}

func (x *synerexSubscribeDemandServer) Send(m *Demand) error {
	return x.ServerStream.SendMsg(m)
}

func _Synerex_SubscribeSupply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Channel)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SynerexServer).SubscribeSupply(m, &synerexSubscribeSupplyServer{stream})
}

type Synerex_SubscribeSupplyServer interface {
	Send(*Supply) error
	grpc.ServerStream
}

type synerexSubscribeSupplyServer struct {
	grpc.ServerStream
}

func (x *synerexSubscribeSupplyServer) Send(m *Supply) error {
	return x.ServerStream.SendMsg(m)
}

func _Synerex_SubscribeMbus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Mbus)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SynerexServer).SubscribeMbus(m, &synerexSubscribeMbusServer{stream})
}

type Synerex_SubscribeMbusServer interface {
	Send(*MbusMsg) error
	grpc.ServerStream
}

type synerexSubscribeMbusServer struct {
	grpc.ServerStream
}

func (x *synerexSubscribeMbusServer) Send(m *MbusMsg) error {
	return x.ServerStream.SendMsg(m)
}

func _Synerex_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MbusMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).SendMsg(ctx, req.(*MbusMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Synerex_CloseMbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mbus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SynerexServer).CloseMbus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Synerex/CloseMbus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SynerexServer).CloseMbus(ctx, req.(*Mbus))
	}
	return interceptor(ctx, in, info, handler)
}

var _Synerex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Synerex",
	HandlerType: (*SynerexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDemand",
			Handler:    _Synerex_RegisterDemand_Handler,
		},
		{
			MethodName: "RegisterSupply",
			Handler:    _Synerex_RegisterSupply_Handler,
		},
		{
			MethodName: "ProposeDemand",
			Handler:    _Synerex_ProposeDemand_Handler,
		},
		{
			MethodName: "ProposeSupply",
			Handler:    _Synerex_ProposeSupply_Handler,
		},
		{
			MethodName: "ReserveSupply",
			Handler:    _Synerex_ReserveSupply_Handler,
		},
		{
			MethodName: "ReserveDemand",
			Handler:    _Synerex_ReserveDemand_Handler,
		},
		{
			MethodName: "SelectSupply",
			Handler:    _Synerex_SelectSupply_Handler,
		},
		{
			MethodName: "SelectDemand",
			Handler:    _Synerex_SelectDemand_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _Synerex_Confirm_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _Synerex_SendMsg_Handler,
		},
		{
			MethodName: "CloseMbus",
			Handler:    _Synerex_CloseMbus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDemand",
			Handler:       _Synerex_SubscribeDemand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSupply",
			Handler:       _Synerex_SubscribeSupply_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMbus",
			Handler:       _Synerex_SubscribeMbus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "synerex.proto",
}
